package backend.Reports;

import backend.prm.report.CampaignReportRow;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import java.io.FileOutputStream;
import java.util.List;

public class CampaignReport {

    public static void generateReport(List<CampaignReportRow> rows,
                                      String startPeriod,
                                      String endPeriod,
                                      String path) {
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();

            Font metaFont = new Font(Font.FontFamily.TIMES_ROMAN, 11);
            Font addressFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);

            PdfPTable headerlayout = new PdfPTable(2);
            headerlayout.setWidthPercentage(100);
            headerlayout.setWidths(new float[]{1, 1});
            headerlayout.getDefaultCell().setBorder(Rectangle.NO_BORDER);

            PdfPCell leftCell = new PdfPCell();
            leftCell.setBorder(Rectangle.NO_BORDER);
            leftCell.addElement(new Paragraph("Start period: " + startPeriod, metaFont));
            leftCell.addElement(new Paragraph("End period: " + endPeriod, metaFont));
            leftCell.addElement(new Paragraph("Campaigns included: " + rows.size(), metaFont));
            headerlayout.addCell(leftCell);

            PdfPCell rightCell = new PdfPCell();
            rightCell.setBorder(Rectangle.NO_BORDER);
            Paragraph address = new Paragraph(
                    "Infinite Solution Ltd.,\nNorthampton Square,\nLondon,\nEC1V 0HB",
                    addressFont
            );
            address.setAlignment(Element.ALIGN_RIGHT);
            rightCell.addElement(address);
            headerlayout.addCell(rightCell);

            document.add(headerlayout);
            document.add(Chunk.NEWLINE);

            Font titleFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD | Font.ITALIC);
            Paragraph title = new Paragraph("Advertising Campaigns Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            PdfPTable table = new PdfPTable(8);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2.2f, 3.2f, 2.2f, 2.2f, 1.8f, 1.8f, 1.8f, 2.0f});

            Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 11, Font.BOLD);
            Font normalFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);

            String[] headers = new String[]{
                    "Campaign", "Title", "Start", "End", "Status", "Hits", "Purchased", "Conversion"
            };

            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, boldFont));
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                cell.setPadding(6);
                table.addCell(cell);
            }

            for (CampaignReportRow r : rows) {
                table.addCell(new PdfPCell(new Phrase(safe(r.getCampaignCode()), normalFont)));
                table.addCell(new PdfPCell(new Phrase(safe(r.getCampaignTitle()), normalFont)));
                table.addCell(new PdfPCell(new Phrase(safeDateTime(r.getStartDateTime()), normalFont)));
                table.addCell(new PdfPCell(new Phrase(safeDateTime(r.getEndDateTime()), normalFont)));
                table.addCell(new PdfPCell(new Phrase(safe(r.getStatus()), normalFont)));
                table.addCell(new PdfPCell(new Phrase(String.valueOf(r.getClickCount()), normalFont)));
                table.addCell(new PdfPCell(new Phrase(String.valueOf(r.getTotalPurchased()), normalFont)));

                String conversion;
                if (r.getClickCount() == 0) {
                    conversion = "N/A";
                } else {
                    double pct = (r.getTotalPurchased() * 100.0) / r.getClickCount();
                    conversion = String.format("%.2f%%", pct);
                }
                table.addCell(new PdfPCell(new Phrase(conversion, normalFont)));
            }

            document.add(table);
            document.add(Chunk.NEWLINE);

            Font footerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
            document.add(new Paragraph("Generated: " + java.time.LocalDate.now(), footerFont));
            document.add(new Paragraph("Generated by IPOS-PU Team 21", footerFont));

            document.close();
            System.out.println("Campaign report saved to: " + path);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static String safe(String v) {
        return (v == null || v.isBlank()) ? "-" : v;
    }

    private static String safeDateTime(java.time.LocalDateTime dt) {
        if (dt == null) return "-";
        // keep it simple/consistent
        return dt.toString().replace('T', ' ');
    }
}