package backend.Reports;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.Document;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.List;


public class EngagementReport {

    public static void generateReport(List<EngagementStats> stats, String campaignId, String campaignDescription, String startPeriod, String endPeriod, String path) {
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();

            Font metaFont = new Font(Font.FontFamily.TIMES_ROMAN, 11);
            Font addressFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);

            //header
            PdfPTable headerlayout = new PdfPTable(2);
            headerlayout.setWidthPercentage(100);
            headerlayout.setWidths(new float[]{1, 1});
            headerlayout.getDefaultCell().setBorder(Rectangle.NO_BORDER);

            PdfPCell leftCell = new PdfPCell();
            leftCell.setBorder(Rectangle.NO_BORDER);
            leftCell.addElement(new Paragraph("Campaign ID: " + campaignId, metaFont));
            leftCell.addElement(new Paragraph("Campaign name: " + campaignDescription, metaFont));
            leftCell.addElement(new Paragraph("Start period: " + startPeriod, metaFont));
            leftCell.addElement(new Paragraph("End period: " + endPeriod, metaFont));
            headerlayout.addCell(leftCell);

            PdfPCell rightCell = new PdfPCell();
            rightCell.setBorder(Rectangle.NO_BORDER);
            Paragraph address = new Paragraph("Infinite Solution Ltd.,\nNorthampton Square,\nLondon,\nEC1V 0HB", addressFont);
            address.setAlignment(Element.ALIGN_RIGHT);
            rightCell.addElement(address);
            headerlayout.addCell(rightCell);

            document.add(headerlayout);
            document.add(Chunk.NEWLINE);

            // Title
            Font titleFont = new Font(Font.FontFamily.TIMES_ROMAN,  16, Font.BOLD | Font.ITALIC);
            Paragraph title = new  Paragraph("Campaign Engagement Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            //table
            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2, 3, 2, 2, 3});

            Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 11, Font.BOLD);
            Font normalFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);

            // headers
            for (String header : new String[]{"Campaign ID", "Description", "Hit count", "Purchases", "Conversion Rate"}) {
                PdfPCell cell = new PdfPCell(new Phrase(header, boldFont));
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                cell.setPadding(6);
                table.addCell(cell);
            }

            for (EngagementStats s : stats) {
                table.addCell(new PdfPCell(new Phrase(s.getCounterId(),  normalFont)));
                table.addCell(new PdfPCell(new Phrase(s.getCounterDescription(),normalFont)));
                table.addCell(new PdfPCell(new Phrase(String.valueOf(s.getHitsCount()),normalFont)));
                String purchases = s.getPurchases() == 0 ? "N/A" : String.valueOf(s.getPurchases());
                table.addCell(new PdfPCell(new Phrase(purchases, normalFont)));
                table.addCell(new PdfPCell(new Phrase(s.getConversionRate(),normalFont)));
            }
            document.add(table);
            document.add(Chunk.NEWLINE);

            //Footer
            Font footerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
            document.add(new Paragraph("Generated: " + java.time.LocalDate.now(), footerFont));
            document.add(new Paragraph("Generated by  IPOS-PU Team 21", footerFont));

            document.close();
            System.out.println("Engagement report saved to: " + path);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
