package backend.Reports;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.Document;

import java.io.FileOutputStream;
import java.util.List;

public class SalesReport {

    public static void generateReport(List<ProductStats> products, String Path, String startPeriod, String endPeriod) {
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(Path));
            document.open();

            //Company Address
            Font addressFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
            Paragraph address = new Paragraph("Infinite Solution Ltd., \nNorthampton Square, \nLondon, \nEC1V 0HB");
            address.setAlignment(Element.ALIGN_RIGHT);
            document.add(address);

            //Title
            Font titleFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD | Font.ITALIC);
            Paragraph title = new Paragraph("Sales Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);

            //Metadata
            Font metaFont = new Font(Font.FontFamily.TIMES_ROMAN, 11);
            document.add(new Paragraph("Start Period: " + startPeriod, metaFont));
            document.add(new Paragraph("End Period: " + endPeriod, metaFont));
            document.add(Chunk.NEWLINE);

            // creating the columns headers
            for (String header : new String[]{"ItemId", "Product Name", "Quantity Sold", "Unit Price (£)", "Total Revenue (£)"}) {
                PdfPCell cell = new PdfPCell(new Phrase(header, new Font(Font.FontFamily.TIMES_ROMAN, 11, Font.BOLD)));
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                cell.setPadding(6);
                table.addCell(cell);
            }

            // loop to put out the rows
            double grandTotal = 0;
            for (ProductStats product : products) {
                table.addCell(product.getItemId());
                table.addCell(product.getProductName());
                table.addCell(String.valueOf(product.getQuantitySold()));
                table.addCell(String.format("%.2f", product.getUnitPrice()));
                table.addCell(String.format("%.2f", product.getTotalRevenue()));
                grandTotal += product.getTotalRevenue();
            }

            //total row
            PdfPCell totalLabel = new PdfPCell(new Phrase("TOTAL", new Font(Font.FontFamily.TIMES_ROMAN, 11, Font.BOLD)));
            totalLabel.setColspan(4);
            totalLabel.setPadding(6);
            table.addCell(totalLabel);

            PdfPCell totalValue = new PdfPCell(new Phrase(String.format("%.2f", grandTotal), new Font(Font.FontFamily.TIMES_ROMAN, 11, Font.BOLD)));
            totalValue.setPadding(6);
            table.addCell(totalValue);

            document.add(table);

            // Footer
            Font footerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
            document.add(new Paragraph("Generated: " + java.time.LocalDate.now(), footerFont));
            document.add(new Paragraph("Generated by IPOS-PU Team 21", footerFont));

            document.close();
            System.out.println("SalesReport made at: " + Path);


        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
